global:
  scrape_interval: 10s
  # How often alert rules are evaluated
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:8080
  - job_name: node
    static_configs:
      - targets:
          - localhost:9100
